import logging
import io
from typing import Optional
from pypdf import PdfReader
from pypdf.errors import PdfReadError

logger = logging.getLogger(__name__)

def extract_text_from_pdf(uploaded_file: bytes) -> Optional[str]:
    """
    Extracts text from an uploaded PDF file (in bytes).
    
    Args:
        uploaded_file (bytes): The raw bytes of the uploaded PDF file.
        
    Returns:
        Optional[str]: The extracted full text content, or None if extraction fails.
    """
    if not uploaded_file:
        logger.warning("Empty file bytes provided for PDF extraction.")
        return None

    try:
        # Load PDF bytes into a file-like object
        pdf_file = io.BytesIO(uploaded_file)
        reader = PdfReader(pdf_file)
        
        extracted_text = []
        
        # Iterate through each page
        for page_num, page in enumerate(reader.pages):
            try:
                text = page.extract_text()
                # Handle empty pages and format it cleanly
                if text and text.strip():
                    extracted_text.append(text.strip())
                else:
                    logger.debug(f"Page {page_num + 1} is empty or contains no extractable text.")
            except Exception as e:
                logger.warning(f"Failed to extract text from page {page_num + 1}: {e}")
                
        # Join the pages with double newlines separating them
        full_text = "\n\n".join(extracted_text)
        
        if not full_text:
            logger.warning("No text could be extracted from the provided PDF.")
            return None
            
        return full_text
        
    except PdfReadError as e:
        logger.error(f"Invalid PDF file or corrupted data: {e}")
        return None
    except Exception as e:
        logger.error(f"Unexpected error during PDF extraction: {e}")
        return None

import re
from typing import List

def chunk_text_optimized(text: str, target_chunk_words: int = 500, overlap_words: int = 100) -> List[str]:
    """
    Splits extracted PDF text into chunks optimized for embeddings by respecting sentence boundaries.
    
    It aggregates sentences until the word count reaches ~target_chunk_words.
    Overlap is generated by pulling forward the trailing sentences of the previous chunk.
    
    Args:
        text (str): The full extracted text.
        target_chunk_words (int): Recommended size (500-800 words).
        overlap_words (int): Overlap window size.
        
    Returns:
        List[str]: A list of clean, embedding-ready text chunks.
    """
    if not text or not text.strip():
        return []

    # Clean whitespace but preserve punctuation formatting
    text = re.sub(r'\s+', ' ', text.strip())
    
    # Split text into sentences intelligently (period, exclamation, question mark followed by space)
    sentences = re.split(r'(?<=[.!?])\s+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    chunks = []
    current_chunk = []
    current_word_count = 0

    for sentence in sentences:
        words_in_sentence = len(sentence.split(' '))
        
        # If a single sentence is bizarrely massive (e.g. malformed PDF string without punctuation), 
        # add it nonetheless and flush chunk immediately after.
        current_chunk.append(sentence)
        current_word_count += words_in_sentence

        # Once we hit or slightly exceed the target word count, finalize the chunk
        if current_word_count >= target_chunk_words:
            chunks.append(" ".join(current_chunk))
            
            # Prepare the structural overlap for the next chunk
            overlap_chunk = []
            overlap_count = 0
            
            # Walk backwards through the current chunk's sentences to gather ~100 words of overlap context
            for past_sentence in reversed(current_chunk):
                past_words = len(past_sentence.split(' '))
                # Ensure we get as close to overlap_words as possible without aggressively exceeding it,
                # but guarantee at least one sentence of overlap if possible.
                if overlap_count + past_words <= overlap_words or not overlap_chunk:
                    overlap_chunk.insert(0, past_sentence)
                    overlap_count += past_words
                else:
                    break
            
            # Seed the next chunk with the calculated overlap
            current_chunk = overlap_chunk
            current_word_count = overlap_count

    # Add any remaining sentences as the final chunk
    if current_chunk and current_word_count > 0:
        final_string = " ".join(current_chunk)
        # Prevent appending tiny exact duplicate overlaps at the end if the text ends perfectly
        if len(chunks) == 0 or final_string not in chunks[-1]:
            chunks.append(final_string)

    return chunks

